version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Unit test
          command: |
            npm install
            npm run coverage
      - store_artifacts:
          path: ./coverage
          destination: artifact-file
