version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Build api
          command: npm install

  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Unit test
          command: |
            npm install
            npm run coverage
      - store_artifacts:
          path: ./coverage
          destination: artifact-file

  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Deploy heroku
          command: |
            npm install
            npm install -g heroku
            docker build -t veiaco-api .
            docker tag veiaco-api registry.heroku.com/veiaco-api/web
            heroku container:login
            docker push registry.heroku.com/veiaco-api/web

workflows:
  version: 2
  pipeline-master:
    jobs:
      - build
      - test
      - deploy
