version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout

      - run:
          name: Build api
          command: npm install

      - run:
          name: Unit test
          command: npm run coverage
      
      - run:
          name: Build Docker image
          command: docker build -t frutuozo29/veiaco-api .
      
      - run:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker push frutuozo29/veiaco-api
      
      - run:
          name: Deploy to heroku
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroko.com
            docker tag frutuozo29/veiaco-api registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
